### ISSUE TITLE
what i need to check?

### ISSUE THREAD

**Issue by PaoloVeloce** [smythtech/WifiProbeMapper#3]
```
root@192:~/WifiProbeMapper# python WPMServer.py -i wlan1mon 
[+] Getting config from config.js
[+] Setting up web socket server...
Traceback (most recent call last):
  File "WPMServer.py", line 156, in <module>
    main()
  File "WPMServer.py", line 150, in main
    http_server.listen(config["serverPort"])root@192:~/WifiProbeMapper# python WPMServer.py -i wlan1mon 
[+] Getting config from config.js
[+] Setting up web socket server...
Traceback (most recent call last):
  File "WPMServer.py", line 156, in <module>
    main()
  File "WPMServer.py", line 150, in main
    http_server.listen(config["serverPort"])
  File "/usr/lib/python2.7/dist-packages/tornado/tcpserver.py", line 143, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/lib/python2.7/dist-packages/tornado/netutil.py", line 122, in bind_sockets
    0, flags)):
socket.error: getaddrinfo() argument 2 must be integer or string
```

**Comment by smythtech** [comment]
Hey man. It looks like it might be having problems reading the port from the config.js file. Could you take a look at your config.js file and make sure there aren't any missing quotes or anything. 

If everything looks ok in the config file, use "netstat -lnpt" to check if the port you specified in the config file is already used by another application. 

Let me know if you're still having problems.
